version: "3"

services:

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.23
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: [ "--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci" ]


