version: "3"

services:

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command:
      - bash
      - -c
      - |
        python manage.py runserver 0.0.0.0:8000


  mysql:
    image: mysql:8.0.23
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    entrypoint:
      - bash
      - -c
      - |
        echo "CREATE DATABASE IF NOT EXISTS $MYSQL_TEST_DATABASE; GRANT ALL ON *.* TO 'user'@'%'; flush privileges;" > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

