version: "3"

services:

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    env_file:
      - .env
    depends_on:
      - mysql
    command: /start

  mysql:
    image: mysql:8.0.23
    restart: always
    env_file:
      - .env
    entrypoint:
      - bash
      - -c
      - |
        echo "CREATE DATABASE IF NOT EXISTS $MYSQL_TEST_DATABASE; GRANT ALL ON *.* TO 'user'@'%'; flush privileges;" > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nginx:
    image: nginx:1.19.5-alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro